name: Sync PocketMine-MP primary branches

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to update'
        required: true
        type: choice
        options:
          - minor-next
          - major-next
          - "*"

jobs:
  merge:
    name: Sync branches
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/PocketMine-MP # to allow testing on forks without editing the workflow
        fetch-depth: 0
        ssh-key: ${{ secrets.POCKETMINE_MP_DEPLOY_KEY }}

    - name: Set Git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com

    - name: Merge "stable" into "minor-next" and push changes
      if: contains(fromJSON('["minor-next", "*"]'), github.event.inputs.branch)
      run: |
        git checkout -f minor-next
        git pull --ff origin stable
        git push

    - name: Merge "minor-next" into "major-next" and push changes
      if: contains(fromJSON('["major-next", "*"]'), github.event.inputs.branch)
      run: |
        git checkout -f major-next
        git pull --ff origin minor-next
        git push
