name: XPocketMP post-release

on:
  workflow_run:
  repository_dispatch:
    types: pocketmine_mp_post_release

jobs:
  post-release:
    name: Update version info post-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout RestrictedActions
        uses: actions/checkout@v4

      - name: Generate access token
        id: token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
          repositories: XPocketMP

      - name: Checkout XPocketMP 
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/XPocketMP # to allow testing on forks without editing the workflow
          fetch-depth: 0
          token: ${{ steps.token.outputs.token }}
          ref: ${{ github.event.client_payload.branch }}
          path: ${{ github.workspace }}/xpocketmp

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.token.outputs.token }}
  
      - name: Set Git config
        working-directory: ${{ github.workspace }}/xpocketmp
        run: |
          git config user.name '${{ steps.token.outputs.app-slug }}[bot]'
          git config user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Run version bump script
        working-directory: ${{ github.workspace }}/xpocketmp
        run: |
          "${{ github.workspace }}/.github/workflows/bump-version-post-release.sh" ./ "Commit created by: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Push changes
        working-directory: ${{ github.workspace }}/xpocketmp
        run: git push

