name: PocketMine-MP post-release

on:
  repository_dispatch:
    types: pocketmine_mp_post_release

jobs:
  post-release:
    name: Update version info post-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout RestrictedActions
        uses: actions/checkout@v4

      - name: Checkout PocketMine-MP
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/PocketMine-MP # to allow testing on forks without editing the workflow
          fetch-depth: 0
          ssh-key: ${{ secrets.POCKETMINE_MP_DEPLOY_KEY }}
          ref: ${{ github.event.client_payload.branch }}
          path: ${{ github.workspace }}/pocketmine-mp


      - name: Set Git config
        working-directory: ${{ github.workspace }}/pocketmine-mp
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Run version bump script
        working-directory: ${{ github.workspace }}/pocketmine-mp
        run: |
          "${{ github.workspace }}/.github/workflows/bump-version-post-release.sh" ./ "Commit created by: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"

      - name: Push changes
        working-directory: ${{ github.workspace }}/pocketmine-mp
        run: git push

